// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// 000_albers_geographiclib.cpp
cpp11::writable::data_frame albers_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles lon0, double stdlat1, double stdlat2, double k1);
extern "C" SEXP _geographiclib_albers_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP stdlat1, SEXP stdlat2, SEXP k1) {
  BEGIN_CPP11
    return cpp11::as_sexp(albers_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat1), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat2), cpp11::as_cpp<cpp11::decay_t<double>>(k1)));
  END_CPP11
}
// 000_albers_geographiclib.cpp
cpp11::writable::data_frame albers_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles lon0, double stdlat1, double stdlat2, double k1);
extern "C" SEXP _geographiclib_albers_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP stdlat1, SEXP stdlat2, SEXP k1) {
  BEGIN_CPP11
    return cpp11::as_sexp(albers_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat1), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat2), cpp11::as_cpp<cpp11::decay_t<double>>(k1)));
  END_CPP11
}
// 000_albers_geographiclib.cpp
cpp11::writable::data_frame albers_fwd_single_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles lon0, double stdlat, double k0);
extern "C" SEXP _geographiclib_albers_fwd_single_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP stdlat, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(albers_fwd_single_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_albers_geographiclib.cpp
cpp11::writable::data_frame albers_rev_single_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles lon0, double stdlat, double k0);
extern "C" SEXP _geographiclib_albers_rev_single_cpp(SEXP x, SEXP y, SEXP lon0, SEXP stdlat, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(albers_rev_single_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_azimuthaleq_geographiclib.cpp
cpp11::writable::data_frame azimuthaleq_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles lon0, cpp11::doubles lat0);
extern "C" SEXP _geographiclib_azimuthaleq_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(azimuthaleq_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat0)));
  END_CPP11
}
// 000_azimuthaleq_geographiclib.cpp
cpp11::writable::data_frame azimuthaleq_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles lon0, cpp11::doubles lat0);
extern "C" SEXP _geographiclib_azimuthaleq_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(azimuthaleq_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat0)));
  END_CPP11
}
// 000_cassinisoldner_geographiclib.cpp
cpp11::writable::data_frame cassini_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, double lon0, double lat0);
extern "C" SEXP _geographiclib_cassini_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(cassini_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0)));
  END_CPP11
}
// 000_cassinisoldner_geographiclib.cpp
cpp11::writable::data_frame cassini_rev_cpp(cpp11::doubles x, cpp11::doubles y, double lon0, double lat0);
extern "C" SEXP _geographiclib_cassini_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(cassini_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::data_frame dms_decode_cpp(cpp11::strings input);
extern "C" SEXP _geographiclib_dms_decode_cpp(SEXP input) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_decode_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(input)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::data_frame dms_decode_latlon_cpp(cpp11::strings dmsa, cpp11::strings dmsb, cpp11::logicals longfirst);
extern "C" SEXP _geographiclib_dms_decode_latlon_cpp(SEXP dmsa, SEXP dmsb, SEXP longfirst) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_decode_latlon_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dmsa), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dmsb), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(longfirst)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::doubles dms_decode_angle_cpp(cpp11::strings input);
extern "C" SEXP _geographiclib_dms_decode_angle_cpp(SEXP input) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_decode_angle_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(input)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::doubles dms_decode_azimuth_cpp(cpp11::strings input);
extern "C" SEXP _geographiclib_dms_decode_azimuth_cpp(SEXP input) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_decode_azimuth_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(input)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::strings dms_encode_cpp(cpp11::doubles angle, cpp11::integers component, cpp11::integers prec, cpp11::integers indicator, cpp11::strings dmssep);
extern "C" SEXP _geographiclib_dms_encode_cpp(SEXP angle, SEXP component, SEXP prec, SEXP indicator, SEXP dmssep) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_encode_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(angle), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(component), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(prec), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(indicator), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dmssep)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::strings dms_encode_auto_cpp(cpp11::doubles angle, cpp11::integers prec, cpp11::integers indicator, cpp11::strings dmssep);
extern "C" SEXP _geographiclib_dms_encode_auto_cpp(SEXP angle, SEXP prec, SEXP indicator, SEXP dmssep) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_encode_auto_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(angle), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(prec), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(indicator), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(dmssep)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::data_frame dms_split_dm_cpp(cpp11::doubles angle);
extern "C" SEXP _geographiclib_dms_split_dm_cpp(SEXP angle) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_split_dm_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(angle)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::data_frame dms_split_dms_cpp(cpp11::doubles angle);
extern "C" SEXP _geographiclib_dms_split_dms_cpp(SEXP angle) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_split_dms_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(angle)));
  END_CPP11
}
// 000_dms_geographiclib.cpp
cpp11::writable::doubles dms_combine_cpp(cpp11::doubles d, cpp11::doubles m, cpp11::doubles s);
extern "C" SEXP _geographiclib_dms_combine_cpp(SEXP d, SEXP m, SEXP s) {
  BEGIN_CPP11
    return cpp11::as_sexp(dms_combine_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(d), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(m), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(s)));
  END_CPP11
}
// 000_ellipsoid_geographiclib.cpp
cpp11::writable::list ellipsoid_params_cpp();
extern "C" SEXP _geographiclib_ellipsoid_params_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(ellipsoid_params_cpp());
  END_CPP11
}
// 000_ellipsoid_geographiclib.cpp
cpp11::writable::data_frame ellipsoid_circle_cpp(cpp11::doubles lat);
extern "C" SEXP _geographiclib_ellipsoid_circle_cpp(SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(ellipsoid_circle_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_ellipsoid_geographiclib.cpp
cpp11::writable::data_frame ellipsoid_latitudes_cpp(cpp11::doubles lat);
extern "C" SEXP _geographiclib_ellipsoid_latitudes_cpp(SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(ellipsoid_latitudes_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_ellipsoid_geographiclib.cpp
cpp11::writable::data_frame ellipsoid_latitudes_inv_cpp(cpp11::doubles lat, cpp11::strings type);
extern "C" SEXP _geographiclib_ellipsoid_latitudes_inv_cpp(SEXP lat, SEXP type) {
  BEGIN_CPP11
    return cpp11::as_sexp(ellipsoid_latitudes_inv_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(type)));
  END_CPP11
}
// 000_ellipsoid_geographiclib.cpp
cpp11::writable::data_frame ellipsoid_curvature_cpp(cpp11::doubles lat);
extern "C" SEXP _geographiclib_ellipsoid_curvature_cpp(SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(ellipsoid_curvature_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_gars_geographiclib.cpp
cpp11::writable::strings gars_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers precision);
extern "C" SEXP _geographiclib_gars_fwd_cpp(SEXP lon, SEXP lat, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(gars_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_gars_geographiclib.cpp
cpp11::writable::data_frame gars_rev_cpp(cpp11::strings gars);
extern "C" SEXP _geographiclib_gars_rev_cpp(SEXP gars) {
  BEGIN_CPP11
    return cpp11::as_sexp(gars_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(gars)));
  END_CPP11
}
// 000_geocentric_geographiclib.cpp
cpp11::writable::data_frame geocentric_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles h);
extern "C" SEXP _geographiclib_geocentric_fwd_cpp(SEXP lon, SEXP lat, SEXP h) {
  BEGIN_CPP11
    return cpp11::as_sexp(geocentric_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(h)));
  END_CPP11
}
// 000_geocentric_geographiclib.cpp
cpp11::writable::data_frame geocentric_rev_cpp(cpp11::doubles X, cpp11::doubles Y, cpp11::doubles Z);
extern "C" SEXP _geographiclib_geocentric_rev_cpp(SEXP X, SEXP Y, SEXP Z) {
  BEGIN_CPP11
    return cpp11::as_sexp(geocentric_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(X), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(Y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(Z)));
  END_CPP11
}
// 000_geocoords_geographiclib.cpp
cpp11::writable::data_frame geocoords_parse_cpp(cpp11::strings input);
extern "C" SEXP _geographiclib_geocoords_parse_cpp(SEXP input) {
  BEGIN_CPP11
    return cpp11::as_sexp(geocoords_parse_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(input)));
  END_CPP11
}
// 000_geocoords_geographiclib.cpp
cpp11::writable::strings geocoords_to_mgrs_cpp(cpp11::doubles lat, cpp11::doubles lon, cpp11::integers precision);
extern "C" SEXP _geographiclib_geocoords_to_mgrs_cpp(SEXP lat, SEXP lon, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(geocoords_to_mgrs_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_geocoords_geographiclib.cpp
cpp11::writable::strings geocoords_to_utm_cpp(cpp11::doubles lat, cpp11::doubles lon, cpp11::integers precision);
extern "C" SEXP _geographiclib_geocoords_to_utm_cpp(SEXP lat, SEXP lon, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(geocoords_to_utm_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_geodesic_geographiclib.cpp
cpp11::writable::data_frame geodesic_direct_fast_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles azi1, cpp11::doubles s12);
extern "C" SEXP _geographiclib_geodesic_direct_fast_cpp(SEXP lon1, SEXP lat1, SEXP azi1, SEXP s12) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_direct_fast_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(azi1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(s12)));
  END_CPP11
}
// 000_geodesic_geographiclib.cpp
cpp11::writable::data_frame geodesic_inverse_fast_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_inverse_fast_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_inverse_fast_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geodesic_geographiclib.cpp
cpp11::writable::data_frame geodesic_path_fast_cpp(double lon1, double lat1, double lon2, double lat2, int n_points);
extern "C" SEXP _geographiclib_geodesic_path_fast_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2, SEXP n_points) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_path_fast_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lon1), cpp11::as_cpp<cpp11::decay_t<double>>(lat1), cpp11::as_cpp<cpp11::decay_t<double>>(lon2), cpp11::as_cpp<cpp11::decay_t<double>>(lat2), cpp11::as_cpp<cpp11::decay_t<int>>(n_points)));
  END_CPP11
}
// 000_geodesic_geographiclib.cpp
cpp11::writable::doubles geodesic_distance_fast_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_distance_fast_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_distance_fast_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geodesic_geographiclib.cpp
cpp11::writable::doubles geodesic_distance_matrix_fast_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_distance_matrix_fast_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_distance_matrix_fast_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::data_frame geodesic_direct_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles azi1, cpp11::doubles s12);
extern "C" SEXP _geographiclib_geodesic_direct_cpp(SEXP lon1, SEXP lat1, SEXP azi1, SEXP s12) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_direct_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(azi1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(s12)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::data_frame geodesic_inverse_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_inverse_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_inverse_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::data_frame geodesic_path_cpp(double lon1, double lat1, double lon2, double lat2, int n_points);
extern "C" SEXP _geographiclib_geodesic_path_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2, SEXP n_points) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_path_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lon1), cpp11::as_cpp<cpp11::decay_t<double>>(lat1), cpp11::as_cpp<cpp11::decay_t<double>>(lon2), cpp11::as_cpp<cpp11::decay_t<double>>(lat2), cpp11::as_cpp<cpp11::decay_t<int>>(n_points)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::data_frame geodesic_line_cpp(double lon1, double lat1, double azi1, cpp11::doubles distances);
extern "C" SEXP _geographiclib_geodesic_line_cpp(SEXP lon1, SEXP lat1, SEXP azi1, SEXP distances) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_line_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lon1), cpp11::as_cpp<cpp11::decay_t<double>>(lat1), cpp11::as_cpp<cpp11::decay_t<double>>(azi1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(distances)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::doubles geodesic_distance_matrix_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_distance_matrix_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_distance_matrix_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geodesicexact_geographiclib.cpp
cpp11::writable::doubles geodesic_distance_pairwise_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_geodesic_distance_pairwise_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(geodesic_distance_pairwise_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_geohash_geographiclib.cpp
cpp11::writable::strings geohash_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers len);
extern "C" SEXP _geographiclib_geohash_fwd_cpp(SEXP lon, SEXP lat, SEXP len) {
  BEGIN_CPP11
    return cpp11::as_sexp(geohash_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(len)));
  END_CPP11
}
// 000_geohash_geographiclib.cpp
cpp11::writable::data_frame geohash_rev_cpp(cpp11::strings geohash);
extern "C" SEXP _geographiclib_geohash_rev_cpp(SEXP geohash) {
  BEGIN_CPP11
    return cpp11::as_sexp(geohash_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(geohash)));
  END_CPP11
}
// 000_geohash_geographiclib.cpp
cpp11::writable::data_frame geohash_resolution_cpp(cpp11::integers len);
extern "C" SEXP _geographiclib_geohash_resolution_cpp(SEXP len) {
  BEGIN_CPP11
    return cpp11::as_sexp(geohash_resolution_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(len)));
  END_CPP11
}
// 000_geohash_geographiclib.cpp
int geohash_length_for_precision_cpp(double resolution);
extern "C" SEXP _geographiclib_geohash_length_for_precision_cpp(SEXP resolution) {
  BEGIN_CPP11
    return cpp11::as_sexp(geohash_length_for_precision_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(resolution)));
  END_CPP11
}
// 000_geohash_geographiclib.cpp
int geohash_length_for_precisions_cpp(double lat_resolution, double lon_resolution);
extern "C" SEXP _geographiclib_geohash_length_for_precisions_cpp(SEXP lat_resolution, SEXP lon_resolution) {
  BEGIN_CPP11
    return cpp11::as_sexp(geohash_length_for_precisions_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lat_resolution), cpp11::as_cpp<cpp11::decay_t<double>>(lon_resolution)));
  END_CPP11
}
// 000_georef_geographiclib.cpp
cpp11::writable::strings georef_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers precision);
extern "C" SEXP _geographiclib_georef_fwd_cpp(SEXP lon, SEXP lat, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(georef_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_georef_geographiclib.cpp
cpp11::writable::data_frame georef_rev_cpp(cpp11::strings georef);
extern "C" SEXP _geographiclib_georef_rev_cpp(SEXP georef) {
  BEGIN_CPP11
    return cpp11::as_sexp(georef_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(georef)));
  END_CPP11
}
// 000_gnomonic_geographiclib.cpp
cpp11::writable::data_frame gnomonic_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, double lon0, double lat0);
extern "C" SEXP _geographiclib_gnomonic_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(gnomonic_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0)));
  END_CPP11
}
// 000_gnomonic_geographiclib.cpp
cpp11::writable::data_frame gnomonic_rev_cpp(cpp11::doubles x, cpp11::doubles y, double lon0, double lat0);
extern "C" SEXP _geographiclib_gnomonic_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP lat0) {
  BEGIN_CPP11
    return cpp11::as_sexp(gnomonic_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0)));
  END_CPP11
}
// 000_lcc_geographiclib.cpp
cpp11::writable::data_frame lcc_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, double lon0, double lat0, double stdlat, double k0);
extern "C" SEXP _geographiclib_lcc_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP lat0, SEXP stdlat, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(lcc_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_lcc_geographiclib.cpp
cpp11::writable::data_frame lcc_fwd2_cpp(cpp11::doubles lon, cpp11::doubles lat, double lon0, double lat0, double stdlat1, double stdlat2, double k1);
extern "C" SEXP _geographiclib_lcc_fwd2_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP lat0, SEXP stdlat1, SEXP stdlat2, SEXP k1) {
  BEGIN_CPP11
    return cpp11::as_sexp(lcc_fwd2_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat1), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat2), cpp11::as_cpp<cpp11::decay_t<double>>(k1)));
  END_CPP11
}
// 000_lcc_geographiclib.cpp
cpp11::writable::data_frame lcc_rev_cpp(cpp11::doubles x, cpp11::doubles y, double lon0, double lat0, double stdlat, double k0);
extern "C" SEXP _geographiclib_lcc_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP lat0, SEXP stdlat, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(lcc_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_lcc_geographiclib.cpp
cpp11::writable::data_frame lcc_rev2_cpp(cpp11::doubles x, cpp11::doubles y, double lon0, double lat0, double stdlat1, double stdlat2, double k1);
extern "C" SEXP _geographiclib_lcc_rev2_cpp(SEXP x, SEXP y, SEXP lon0, SEXP lat0, SEXP stdlat1, SEXP stdlat2, SEXP k1) {
  BEGIN_CPP11
    return cpp11::as_sexp(lcc_rev2_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat1), cpp11::as_cpp<cpp11::decay_t<double>>(stdlat2), cpp11::as_cpp<cpp11::decay_t<double>>(k1)));
  END_CPP11
}
// 000_localcartesian_geographiclib.cpp
cpp11::writable::data_frame localcartesian_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles h, double lon0, double lat0, double h0);
extern "C" SEXP _geographiclib_localcartesian_fwd_cpp(SEXP lon, SEXP lat, SEXP h, SEXP lon0, SEXP lat0, SEXP h0) {
  BEGIN_CPP11
    return cpp11::as_sexp(localcartesian_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(h), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(h0)));
  END_CPP11
}
// 000_localcartesian_geographiclib.cpp
cpp11::writable::data_frame localcartesian_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles z, double lon0, double lat0, double h0);
extern "C" SEXP _geographiclib_localcartesian_rev_cpp(SEXP x, SEXP y, SEXP z, SEXP lon0, SEXP lat0, SEXP h0) {
  BEGIN_CPP11
    return cpp11::as_sexp(localcartesian_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(z), cpp11::as_cpp<cpp11::decay_t<double>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(lat0), cpp11::as_cpp<cpp11::decay_t<double>>(h0)));
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::strings mgrs_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers precision);
extern "C" SEXP _geographiclib_mgrs_fwd_cpp(SEXP lon, SEXP lat, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::writable::data_frame mgrs_rev_cpp(cpp11::strings mgrs);
extern "C" SEXP _geographiclib_mgrs_rev_cpp(SEXP mgrs) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(mgrs)));
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::strings mgrs_decode_cpp(cpp11::strings mgrs);
extern "C" SEXP _geographiclib_mgrs_decode_cpp(SEXP mgrs) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_decode_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(mgrs)));
  END_CPP11
}
// 000_osgb_geographiclib.cpp
cpp11::writable::data_frame osgb_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat);
extern "C" SEXP _geographiclib_osgb_fwd_cpp(SEXP lon, SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(osgb_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_osgb_geographiclib.cpp
cpp11::writable::data_frame osgb_rev_cpp(cpp11::doubles easting, cpp11::doubles northing);
extern "C" SEXP _geographiclib_osgb_rev_cpp(SEXP easting, SEXP northing) {
  BEGIN_CPP11
    return cpp11::as_sexp(osgb_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(easting), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(northing)));
  END_CPP11
}
// 000_osgb_geographiclib.cpp
cpp11::writable::strings osgb_gridref_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers precision);
extern "C" SEXP _geographiclib_osgb_gridref_cpp(SEXP lon, SEXP lat, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(osgb_gridref_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_osgb_geographiclib.cpp
cpp11::writable::data_frame osgb_gridref_rev_cpp(cpp11::strings gridref);
extern "C" SEXP _geographiclib_osgb_gridref_rev_cpp(SEXP gridref) {
  BEGIN_CPP11
    return cpp11::as_sexp(osgb_gridref_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(gridref)));
  END_CPP11
}
// 000_polarstereo_geographiclib.cpp
cpp11::writable::data_frame polarstereo_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::logicals northp, double k0);
extern "C" SEXP _geographiclib_polarstereo_fwd_cpp(SEXP lon, SEXP lat, SEXP northp, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(polarstereo_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_polarstereo_geographiclib.cpp
cpp11::writable::data_frame polarstereo_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::logicals northp, double k0);
extern "C" SEXP _geographiclib_polarstereo_rev_cpp(SEXP x, SEXP y, SEXP northp, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(polarstereo_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_polarstereo_geographiclib.cpp
cpp11::writable::data_frame polarstereo_fwd_custom_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::logicals northp, double k0);
extern "C" SEXP _geographiclib_polarstereo_fwd_custom_cpp(SEXP lon, SEXP lat, SEXP northp, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(polarstereo_fwd_custom_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_polarstereo_geographiclib.cpp
cpp11::writable::data_frame polarstereo_rev_custom_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::logicals northp, double k0);
extern "C" SEXP _geographiclib_polarstereo_rev_custom_cpp(SEXP x, SEXP y, SEXP northp, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(polarstereo_rev_custom_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_polygonarea_geographiclib.cpp
cpp11::writable::data_frame polygonarea_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers id, bool polyline);
extern "C" SEXP _geographiclib_polygonarea_cpp(SEXP lon, SEXP lat, SEXP id, SEXP polyline) {
  BEGIN_CPP11
    return cpp11::as_sexp(polygonarea_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(id), cpp11::as_cpp<cpp11::decay_t<bool>>(polyline)));
  END_CPP11
}
// 000_polygonarea_geographiclib.cpp
cpp11::writable::list polygonarea_single_cpp(cpp11::doubles lon, cpp11::doubles lat, bool polyline);
extern "C" SEXP _geographiclib_polygonarea_single_cpp(SEXP lon, SEXP lat, SEXP polyline) {
  BEGIN_CPP11
    return cpp11::as_sexp(polygonarea_single_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<bool>>(polyline)));
  END_CPP11
}
// 000_polygonarea_geographiclib.cpp
cpp11::writable::data_frame polygonarea_cumulative_cpp(cpp11::doubles lon, cpp11::doubles lat, bool polyline);
extern "C" SEXP _geographiclib_polygonarea_cumulative_cpp(SEXP lon, SEXP lat, SEXP polyline) {
  BEGIN_CPP11
    return cpp11::as_sexp(polygonarea_cumulative_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<bool>>(polyline)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::data_frame rhumb_direct_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles azi12, cpp11::doubles s12);
extern "C" SEXP _geographiclib_rhumb_direct_cpp(SEXP lon1, SEXP lat1, SEXP azi12, SEXP s12) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_direct_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(azi12), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(s12)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::data_frame rhumb_inverse_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_rhumb_inverse_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_inverse_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::data_frame rhumb_path_cpp(double lon1, double lat1, double lon2, double lat2, int n_points);
extern "C" SEXP _geographiclib_rhumb_path_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2, SEXP n_points) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_path_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lon1), cpp11::as_cpp<cpp11::decay_t<double>>(lat1), cpp11::as_cpp<cpp11::decay_t<double>>(lon2), cpp11::as_cpp<cpp11::decay_t<double>>(lat2), cpp11::as_cpp<cpp11::decay_t<int>>(n_points)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::data_frame rhumb_line_cpp(double lon1, double lat1, double azi12, cpp11::doubles distances);
extern "C" SEXP _geographiclib_rhumb_line_cpp(SEXP lon1, SEXP lat1, SEXP azi12, SEXP distances) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_line_cpp(cpp11::as_cpp<cpp11::decay_t<double>>(lon1), cpp11::as_cpp<cpp11::decay_t<double>>(lat1), cpp11::as_cpp<cpp11::decay_t<double>>(azi12), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(distances)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::doubles rhumb_distance_pairwise_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_rhumb_distance_pairwise_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_distance_pairwise_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_rhumb_geographiclib.cpp
cpp11::writable::doubles rhumb_distance_matrix_cpp(cpp11::doubles lon1, cpp11::doubles lat1, cpp11::doubles lon2, cpp11::doubles lat2);
extern "C" SEXP _geographiclib_rhumb_distance_matrix_cpp(SEXP lon1, SEXP lat1, SEXP lon2, SEXP lat2) {
  BEGIN_CPP11
    return cpp11::as_sexp(rhumb_distance_matrix_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat1), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon2), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat2)));
  END_CPP11
}
// 000_tm_geographiclib.cpp
cpp11::writable::data_frame tm_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles lon0, double k0);
extern "C" SEXP _geographiclib_tm_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(tm_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_tm_geographiclib.cpp
cpp11::writable::data_frame tm_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles lon0, double k0);
extern "C" SEXP _geographiclib_tm_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(tm_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_tm_geographiclib.cpp
cpp11::writable::data_frame tm_exact_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::doubles lon0, double k0);
extern "C" SEXP _geographiclib_tm_exact_fwd_cpp(SEXP lon, SEXP lat, SEXP lon0, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(tm_exact_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_tm_geographiclib.cpp
cpp11::writable::data_frame tm_exact_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::doubles lon0, double k0);
extern "C" SEXP _geographiclib_tm_exact_rev_cpp(SEXP x, SEXP y, SEXP lon0, SEXP k0) {
  BEGIN_CPP11
    return cpp11::as_sexp(tm_exact_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon0), cpp11::as_cpp<cpp11::decay_t<double>>(k0)));
  END_CPP11
}
// 000_utm_ups.cpp
cpp11::writable::data_frame utmups_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat);
extern "C" SEXP _geographiclib_utmups_fwd_cpp(SEXP lon, SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(utmups_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_utm_ups.cpp
cpp11::writable::data_frame utmups_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::integers zone, cpp11::logicals northp);
extern "C" SEXP _geographiclib_utmups_rev_cpp(SEXP x, SEXP y, SEXP zone, SEXP northp) {
  BEGIN_CPP11
    return cpp11::as_sexp(utmups_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(zone), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_geographiclib_albers_fwd_cpp",                    (DL_FUNC) &_geographiclib_albers_fwd_cpp,                    6},
    {"_geographiclib_albers_fwd_single_cpp",             (DL_FUNC) &_geographiclib_albers_fwd_single_cpp,             5},
    {"_geographiclib_albers_rev_cpp",                    (DL_FUNC) &_geographiclib_albers_rev_cpp,                    6},
    {"_geographiclib_albers_rev_single_cpp",             (DL_FUNC) &_geographiclib_albers_rev_single_cpp,             5},
    {"_geographiclib_azimuthaleq_fwd_cpp",               (DL_FUNC) &_geographiclib_azimuthaleq_fwd_cpp,               4},
    {"_geographiclib_azimuthaleq_rev_cpp",               (DL_FUNC) &_geographiclib_azimuthaleq_rev_cpp,               4},
    {"_geographiclib_cassini_fwd_cpp",                   (DL_FUNC) &_geographiclib_cassini_fwd_cpp,                   4},
    {"_geographiclib_cassini_rev_cpp",                   (DL_FUNC) &_geographiclib_cassini_rev_cpp,                   4},
    {"_geographiclib_dms_combine_cpp",                   (DL_FUNC) &_geographiclib_dms_combine_cpp,                   3},
    {"_geographiclib_dms_decode_angle_cpp",              (DL_FUNC) &_geographiclib_dms_decode_angle_cpp,              1},
    {"_geographiclib_dms_decode_azimuth_cpp",            (DL_FUNC) &_geographiclib_dms_decode_azimuth_cpp,            1},
    {"_geographiclib_dms_decode_cpp",                    (DL_FUNC) &_geographiclib_dms_decode_cpp,                    1},
    {"_geographiclib_dms_decode_latlon_cpp",             (DL_FUNC) &_geographiclib_dms_decode_latlon_cpp,             3},
    {"_geographiclib_dms_encode_auto_cpp",               (DL_FUNC) &_geographiclib_dms_encode_auto_cpp,               4},
    {"_geographiclib_dms_encode_cpp",                    (DL_FUNC) &_geographiclib_dms_encode_cpp,                    5},
    {"_geographiclib_dms_split_dm_cpp",                  (DL_FUNC) &_geographiclib_dms_split_dm_cpp,                  1},
    {"_geographiclib_dms_split_dms_cpp",                 (DL_FUNC) &_geographiclib_dms_split_dms_cpp,                 1},
    {"_geographiclib_ellipsoid_circle_cpp",              (DL_FUNC) &_geographiclib_ellipsoid_circle_cpp,              1},
    {"_geographiclib_ellipsoid_curvature_cpp",           (DL_FUNC) &_geographiclib_ellipsoid_curvature_cpp,           1},
    {"_geographiclib_ellipsoid_latitudes_cpp",           (DL_FUNC) &_geographiclib_ellipsoid_latitudes_cpp,           1},
    {"_geographiclib_ellipsoid_latitudes_inv_cpp",       (DL_FUNC) &_geographiclib_ellipsoid_latitudes_inv_cpp,       2},
    {"_geographiclib_ellipsoid_params_cpp",              (DL_FUNC) &_geographiclib_ellipsoid_params_cpp,              0},
    {"_geographiclib_gars_fwd_cpp",                      (DL_FUNC) &_geographiclib_gars_fwd_cpp,                      3},
    {"_geographiclib_gars_rev_cpp",                      (DL_FUNC) &_geographiclib_gars_rev_cpp,                      1},
    {"_geographiclib_geocentric_fwd_cpp",                (DL_FUNC) &_geographiclib_geocentric_fwd_cpp,                3},
    {"_geographiclib_geocentric_rev_cpp",                (DL_FUNC) &_geographiclib_geocentric_rev_cpp,                3},
    {"_geographiclib_geocoords_parse_cpp",               (DL_FUNC) &_geographiclib_geocoords_parse_cpp,               1},
    {"_geographiclib_geocoords_to_mgrs_cpp",             (DL_FUNC) &_geographiclib_geocoords_to_mgrs_cpp,             3},
    {"_geographiclib_geocoords_to_utm_cpp",              (DL_FUNC) &_geographiclib_geocoords_to_utm_cpp,              3},
    {"_geographiclib_geodesic_direct_cpp",               (DL_FUNC) &_geographiclib_geodesic_direct_cpp,               4},
    {"_geographiclib_geodesic_direct_fast_cpp",          (DL_FUNC) &_geographiclib_geodesic_direct_fast_cpp,          4},
    {"_geographiclib_geodesic_distance_fast_cpp",        (DL_FUNC) &_geographiclib_geodesic_distance_fast_cpp,        4},
    {"_geographiclib_geodesic_distance_matrix_cpp",      (DL_FUNC) &_geographiclib_geodesic_distance_matrix_cpp,      4},
    {"_geographiclib_geodesic_distance_matrix_fast_cpp", (DL_FUNC) &_geographiclib_geodesic_distance_matrix_fast_cpp, 4},
    {"_geographiclib_geodesic_distance_pairwise_cpp",    (DL_FUNC) &_geographiclib_geodesic_distance_pairwise_cpp,    4},
    {"_geographiclib_geodesic_inverse_cpp",              (DL_FUNC) &_geographiclib_geodesic_inverse_cpp,              4},
    {"_geographiclib_geodesic_inverse_fast_cpp",         (DL_FUNC) &_geographiclib_geodesic_inverse_fast_cpp,         4},
    {"_geographiclib_geodesic_line_cpp",                 (DL_FUNC) &_geographiclib_geodesic_line_cpp,                 4},
    {"_geographiclib_geodesic_path_cpp",                 (DL_FUNC) &_geographiclib_geodesic_path_cpp,                 5},
    {"_geographiclib_geodesic_path_fast_cpp",            (DL_FUNC) &_geographiclib_geodesic_path_fast_cpp,            5},
    {"_geographiclib_geohash_fwd_cpp",                   (DL_FUNC) &_geographiclib_geohash_fwd_cpp,                   3},
    {"_geographiclib_geohash_length_for_precision_cpp",  (DL_FUNC) &_geographiclib_geohash_length_for_precision_cpp,  1},
    {"_geographiclib_geohash_length_for_precisions_cpp", (DL_FUNC) &_geographiclib_geohash_length_for_precisions_cpp, 2},
    {"_geographiclib_geohash_resolution_cpp",            (DL_FUNC) &_geographiclib_geohash_resolution_cpp,            1},
    {"_geographiclib_geohash_rev_cpp",                   (DL_FUNC) &_geographiclib_geohash_rev_cpp,                   1},
    {"_geographiclib_georef_fwd_cpp",                    (DL_FUNC) &_geographiclib_georef_fwd_cpp,                    3},
    {"_geographiclib_georef_rev_cpp",                    (DL_FUNC) &_geographiclib_georef_rev_cpp,                    1},
    {"_geographiclib_gnomonic_fwd_cpp",                  (DL_FUNC) &_geographiclib_gnomonic_fwd_cpp,                  4},
    {"_geographiclib_gnomonic_rev_cpp",                  (DL_FUNC) &_geographiclib_gnomonic_rev_cpp,                  4},
    {"_geographiclib_lcc_fwd2_cpp",                      (DL_FUNC) &_geographiclib_lcc_fwd2_cpp,                      7},
    {"_geographiclib_lcc_fwd_cpp",                       (DL_FUNC) &_geographiclib_lcc_fwd_cpp,                       6},
    {"_geographiclib_lcc_rev2_cpp",                      (DL_FUNC) &_geographiclib_lcc_rev2_cpp,                      7},
    {"_geographiclib_lcc_rev_cpp",                       (DL_FUNC) &_geographiclib_lcc_rev_cpp,                       6},
    {"_geographiclib_localcartesian_fwd_cpp",            (DL_FUNC) &_geographiclib_localcartesian_fwd_cpp,            6},
    {"_geographiclib_localcartesian_rev_cpp",            (DL_FUNC) &_geographiclib_localcartesian_rev_cpp,            6},
    {"_geographiclib_mgrs_decode_cpp",                   (DL_FUNC) &_geographiclib_mgrs_decode_cpp,                   1},
    {"_geographiclib_mgrs_fwd_cpp",                      (DL_FUNC) &_geographiclib_mgrs_fwd_cpp,                      3},
    {"_geographiclib_mgrs_rev_cpp",                      (DL_FUNC) &_geographiclib_mgrs_rev_cpp,                      1},
    {"_geographiclib_osgb_fwd_cpp",                      (DL_FUNC) &_geographiclib_osgb_fwd_cpp,                      2},
    {"_geographiclib_osgb_gridref_cpp",                  (DL_FUNC) &_geographiclib_osgb_gridref_cpp,                  3},
    {"_geographiclib_osgb_gridref_rev_cpp",              (DL_FUNC) &_geographiclib_osgb_gridref_rev_cpp,              1},
    {"_geographiclib_osgb_rev_cpp",                      (DL_FUNC) &_geographiclib_osgb_rev_cpp,                      2},
    {"_geographiclib_polarstereo_fwd_cpp",               (DL_FUNC) &_geographiclib_polarstereo_fwd_cpp,               4},
    {"_geographiclib_polarstereo_fwd_custom_cpp",        (DL_FUNC) &_geographiclib_polarstereo_fwd_custom_cpp,        4},
    {"_geographiclib_polarstereo_rev_cpp",               (DL_FUNC) &_geographiclib_polarstereo_rev_cpp,               4},
    {"_geographiclib_polarstereo_rev_custom_cpp",        (DL_FUNC) &_geographiclib_polarstereo_rev_custom_cpp,        4},
    {"_geographiclib_polygonarea_cpp",                   (DL_FUNC) &_geographiclib_polygonarea_cpp,                   4},
    {"_geographiclib_polygonarea_cumulative_cpp",        (DL_FUNC) &_geographiclib_polygonarea_cumulative_cpp,        3},
    {"_geographiclib_polygonarea_single_cpp",            (DL_FUNC) &_geographiclib_polygonarea_single_cpp,            3},
    {"_geographiclib_rhumb_direct_cpp",                  (DL_FUNC) &_geographiclib_rhumb_direct_cpp,                  4},
    {"_geographiclib_rhumb_distance_matrix_cpp",         (DL_FUNC) &_geographiclib_rhumb_distance_matrix_cpp,         4},
    {"_geographiclib_rhumb_distance_pairwise_cpp",       (DL_FUNC) &_geographiclib_rhumb_distance_pairwise_cpp,       4},
    {"_geographiclib_rhumb_inverse_cpp",                 (DL_FUNC) &_geographiclib_rhumb_inverse_cpp,                 4},
    {"_geographiclib_rhumb_line_cpp",                    (DL_FUNC) &_geographiclib_rhumb_line_cpp,                    4},
    {"_geographiclib_rhumb_path_cpp",                    (DL_FUNC) &_geographiclib_rhumb_path_cpp,                    5},
    {"_geographiclib_tm_exact_fwd_cpp",                  (DL_FUNC) &_geographiclib_tm_exact_fwd_cpp,                  4},
    {"_geographiclib_tm_exact_rev_cpp",                  (DL_FUNC) &_geographiclib_tm_exact_rev_cpp,                  4},
    {"_geographiclib_tm_fwd_cpp",                        (DL_FUNC) &_geographiclib_tm_fwd_cpp,                        4},
    {"_geographiclib_tm_rev_cpp",                        (DL_FUNC) &_geographiclib_tm_rev_cpp,                        4},
    {"_geographiclib_utmups_fwd_cpp",                    (DL_FUNC) &_geographiclib_utmups_fwd_cpp,                    2},
    {"_geographiclib_utmups_rev_cpp",                    (DL_FUNC) &_geographiclib_utmups_rev_cpp,                    4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_geographiclib(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
