// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// 000_lcc_geographiclib.cpp
int lcc_cpp();
extern "C" SEXP _geographiclib_lcc_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(lcc_cpp());
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::strings mgrs_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat, cpp11::integers precision);
extern "C" SEXP _geographiclib_mgrs_fwd_cpp(SEXP lon, SEXP lat, SEXP precision) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(precision)));
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::writable::data_frame mgrs_rev_cpp(cpp11::strings mgrs);
extern "C" SEXP _geographiclib_mgrs_rev_cpp(SEXP mgrs) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(mgrs)));
  END_CPP11
}
// 000_mgrs_geographiclib.cpp
cpp11::strings mgrs_decode_cpp(cpp11::strings mgrs);
extern "C" SEXP _geographiclib_mgrs_decode_cpp(SEXP mgrs) {
  BEGIN_CPP11
    return cpp11::as_sexp(mgrs_decode_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(mgrs)));
  END_CPP11
}
// 000_polygonarea_geographiclib.cpp
cpp11::doubles polygonarea_cpp();
extern "C" SEXP _geographiclib_polygonarea_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(polygonarea_cpp());
  END_CPP11
}
// 000_utm_ups.cpp
cpp11::writable::data_frame utmups_fwd_cpp(cpp11::doubles lon, cpp11::doubles lat);
extern "C" SEXP _geographiclib_utmups_fwd_cpp(SEXP lon, SEXP lat) {
  BEGIN_CPP11
    return cpp11::as_sexp(utmups_fwd_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lon), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lat)));
  END_CPP11
}
// 000_utm_ups.cpp
cpp11::writable::data_frame utmups_rev_cpp(cpp11::doubles x, cpp11::doubles y, cpp11::integers zone, cpp11::logicals northp);
extern "C" SEXP _geographiclib_utmups_rev_cpp(SEXP x, SEXP y, SEXP zone, SEXP northp) {
  BEGIN_CPP11
    return cpp11::as_sexp(utmups_rev_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(zone), cpp11::as_cpp<cpp11::decay_t<cpp11::logicals>>(northp)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_geographiclib_lcc_cpp",         (DL_FUNC) &_geographiclib_lcc_cpp,         0},
    {"_geographiclib_mgrs_decode_cpp", (DL_FUNC) &_geographiclib_mgrs_decode_cpp, 1},
    {"_geographiclib_mgrs_fwd_cpp",    (DL_FUNC) &_geographiclib_mgrs_fwd_cpp,    3},
    {"_geographiclib_mgrs_rev_cpp",    (DL_FUNC) &_geographiclib_mgrs_rev_cpp,    1},
    {"_geographiclib_polygonarea_cpp", (DL_FUNC) &_geographiclib_polygonarea_cpp, 0},
    {"_geographiclib_utmups_fwd_cpp",  (DL_FUNC) &_geographiclib_utmups_fwd_cpp,  2},
    {"_geographiclib_utmups_rev_cpp",  (DL_FUNC) &_geographiclib_utmups_rev_cpp,  4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_geographiclib(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
