# Generated by cpp11: do not edit by hand

albers_fwd_cpp <- function(lon, lat, lon0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_albers_fwd_cpp`, lon, lat, lon0, stdlat1, stdlat2, k1)
}

albers_rev_cpp <- function(x, y, lon0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_albers_rev_cpp`, x, y, lon0, stdlat1, stdlat2, k1)
}

albers_fwd_single_cpp <- function(lon, lat, lon0, stdlat, k0) {
  .Call(`_geographiclib_albers_fwd_single_cpp`, lon, lat, lon0, stdlat, k0)
}

albers_rev_single_cpp <- function(x, y, lon0, stdlat, k0) {
  .Call(`_geographiclib_albers_rev_single_cpp`, x, y, lon0, stdlat, k0)
}

azimuthaleq_fwd_cpp <- function(lon, lat, lon0, lat0) {
  .Call(`_geographiclib_azimuthaleq_fwd_cpp`, lon, lat, lon0, lat0)
}

azimuthaleq_rev_cpp <- function(x, y, lon0, lat0) {
  .Call(`_geographiclib_azimuthaleq_rev_cpp`, x, y, lon0, lat0)
}

cassini_fwd_cpp <- function(lon, lat, lon0, lat0) {
  .Call(`_geographiclib_cassini_fwd_cpp`, lon, lat, lon0, lat0)
}

cassini_rev_cpp <- function(x, y, lon0, lat0) {
  .Call(`_geographiclib_cassini_rev_cpp`, x, y, lon0, lat0)
}

ellipsoid_params_cpp <- function() {
  .Call(`_geographiclib_ellipsoid_params_cpp`)
}

ellipsoid_circle_cpp <- function(lat) {
  .Call(`_geographiclib_ellipsoid_circle_cpp`, lat)
}

ellipsoid_latitudes_cpp <- function(lat) {
  .Call(`_geographiclib_ellipsoid_latitudes_cpp`, lat)
}

ellipsoid_latitudes_inv_cpp <- function(lat, type) {
  .Call(`_geographiclib_ellipsoid_latitudes_inv_cpp`, lat, type)
}

ellipsoid_curvature_cpp <- function(lat) {
  .Call(`_geographiclib_ellipsoid_curvature_cpp`, lat)
}

gars_fwd_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_gars_fwd_cpp`, lon, lat, precision)
}

gars_rev_cpp <- function(gars) {
  .Call(`_geographiclib_gars_rev_cpp`, gars)
}

geocentric_fwd_cpp <- function(lon, lat, h) {
  .Call(`_geographiclib_geocentric_fwd_cpp`, lon, lat, h)
}

geocentric_rev_cpp <- function(X, Y, Z) {
  .Call(`_geographiclib_geocentric_rev_cpp`, X, Y, Z)
}

geocoords_parse_cpp <- function(input) {
  .Call(`_geographiclib_geocoords_parse_cpp`, input)
}

geocoords_to_mgrs_cpp <- function(lat, lon, precision) {
  .Call(`_geographiclib_geocoords_to_mgrs_cpp`, lat, lon, precision)
}

geocoords_to_utm_cpp <- function(lat, lon, precision) {
  .Call(`_geographiclib_geocoords_to_utm_cpp`, lat, lon, precision)
}

geodesic_direct_fast_cpp <- function(lon1, lat1, azi1, s12) {
  .Call(`_geographiclib_geodesic_direct_fast_cpp`, lon1, lat1, azi1, s12)
}

geodesic_inverse_fast_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_inverse_fast_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_path_fast_cpp <- function(lon1, lat1, lon2, lat2, n_points) {
  .Call(`_geographiclib_geodesic_path_fast_cpp`, lon1, lat1, lon2, lat2, n_points)
}

geodesic_distance_fast_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_fast_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_distance_matrix_fast_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_matrix_fast_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_direct_cpp <- function(lon1, lat1, azi1, s12) {
  .Call(`_geographiclib_geodesic_direct_cpp`, lon1, lat1, azi1, s12)
}

geodesic_inverse_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_inverse_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_path_cpp <- function(lon1, lat1, lon2, lat2, n_points) {
  .Call(`_geographiclib_geodesic_path_cpp`, lon1, lat1, lon2, lat2, n_points)
}

geodesic_line_cpp <- function(lon1, lat1, azi1, distances) {
  .Call(`_geographiclib_geodesic_line_cpp`, lon1, lat1, azi1, distances)
}

geodesic_distance_matrix_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_matrix_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_distance_pairwise_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_pairwise_cpp`, lon1, lat1, lon2, lat2)
}

geohash_fwd_cpp <- function(lon, lat, len) {
  .Call(`_geographiclib_geohash_fwd_cpp`, lon, lat, len)
}

geohash_rev_cpp <- function(geohash) {
  .Call(`_geographiclib_geohash_rev_cpp`, geohash)
}

geohash_resolution_cpp <- function(len) {
  .Call(`_geographiclib_geohash_resolution_cpp`, len)
}

geohash_length_for_precision_cpp <- function(resolution) {
  .Call(`_geographiclib_geohash_length_for_precision_cpp`, resolution)
}

geohash_length_for_precisions_cpp <- function(lat_resolution, lon_resolution) {
  .Call(`_geographiclib_geohash_length_for_precisions_cpp`, lat_resolution, lon_resolution)
}

georef_fwd_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_georef_fwd_cpp`, lon, lat, precision)
}

georef_rev_cpp <- function(georef) {
  .Call(`_geographiclib_georef_rev_cpp`, georef)
}

gnomonic_fwd_cpp <- function(lon, lat, lon0, lat0) {
  .Call(`_geographiclib_gnomonic_fwd_cpp`, lon, lat, lon0, lat0)
}

gnomonic_rev_cpp <- function(x, y, lon0, lat0) {
  .Call(`_geographiclib_gnomonic_rev_cpp`, x, y, lon0, lat0)
}

lcc_fwd_cpp <- function(lon, lat, lon0, lat0, stdlat, k0) {
  .Call(`_geographiclib_lcc_fwd_cpp`, lon, lat, lon0, lat0, stdlat, k0)
}

lcc_fwd2_cpp <- function(lon, lat, lon0, lat0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_lcc_fwd2_cpp`, lon, lat, lon0, lat0, stdlat1, stdlat2, k1)
}

lcc_rev_cpp <- function(x, y, lon0, lat0, stdlat, k0) {
  .Call(`_geographiclib_lcc_rev_cpp`, x, y, lon0, lat0, stdlat, k0)
}

lcc_rev2_cpp <- function(x, y, lon0, lat0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_lcc_rev2_cpp`, x, y, lon0, lat0, stdlat1, stdlat2, k1)
}

localcartesian_fwd_cpp <- function(lon, lat, h, lon0, lat0, h0) {
  .Call(`_geographiclib_localcartesian_fwd_cpp`, lon, lat, h, lon0, lat0, h0)
}

localcartesian_rev_cpp <- function(x, y, z, lon0, lat0, h0) {
  .Call(`_geographiclib_localcartesian_rev_cpp`, x, y, z, lon0, lat0, h0)
}

mgrs_fwd_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_mgrs_fwd_cpp`, lon, lat, precision)
}

mgrs_rev_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_rev_cpp`, mgrs)
}

mgrs_decode_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_decode_cpp`, mgrs)
}

osgb_fwd_cpp <- function(lon, lat) {
  .Call(`_geographiclib_osgb_fwd_cpp`, lon, lat)
}

osgb_rev_cpp <- function(easting, northing) {
  .Call(`_geographiclib_osgb_rev_cpp`, easting, northing)
}

osgb_gridref_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_osgb_gridref_cpp`, lon, lat, precision)
}

osgb_gridref_rev_cpp <- function(gridref) {
  .Call(`_geographiclib_osgb_gridref_rev_cpp`, gridref)
}

polarstereo_fwd_cpp <- function(lon, lat, northp, k0) {
  .Call(`_geographiclib_polarstereo_fwd_cpp`, lon, lat, northp, k0)
}

polarstereo_rev_cpp <- function(x, y, northp, k0) {
  .Call(`_geographiclib_polarstereo_rev_cpp`, x, y, northp, k0)
}

polarstereo_fwd_custom_cpp <- function(lon, lat, northp, k0) {
  .Call(`_geographiclib_polarstereo_fwd_custom_cpp`, lon, lat, northp, k0)
}

polarstereo_rev_custom_cpp <- function(x, y, northp, k0) {
  .Call(`_geographiclib_polarstereo_rev_custom_cpp`, x, y, northp, k0)
}

polygonarea_cpp <- function(lon, lat, id, polyline) {
  .Call(`_geographiclib_polygonarea_cpp`, lon, lat, id, polyline)
}

polygonarea_single_cpp <- function(lon, lat, polyline) {
  .Call(`_geographiclib_polygonarea_single_cpp`, lon, lat, polyline)
}

polygonarea_cumulative_cpp <- function(lon, lat, polyline) {
  .Call(`_geographiclib_polygonarea_cumulative_cpp`, lon, lat, polyline)
}

rhumb_direct_cpp <- function(lon1, lat1, azi12, s12) {
  .Call(`_geographiclib_rhumb_direct_cpp`, lon1, lat1, azi12, s12)
}

rhumb_inverse_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_inverse_cpp`, lon1, lat1, lon2, lat2)
}

rhumb_path_cpp <- function(lon1, lat1, lon2, lat2, n_points) {
  .Call(`_geographiclib_rhumb_path_cpp`, lon1, lat1, lon2, lat2, n_points)
}

rhumb_line_cpp <- function(lon1, lat1, azi12, distances) {
  .Call(`_geographiclib_rhumb_line_cpp`, lon1, lat1, azi12, distances)
}

rhumb_distance_pairwise_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_distance_pairwise_cpp`, lon1, lat1, lon2, lat2)
}

rhumb_distance_matrix_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_distance_matrix_cpp`, lon1, lat1, lon2, lat2)
}

tm_fwd_cpp <- function(lon, lat, lon0, k0) {
  .Call(`_geographiclib_tm_fwd_cpp`, lon, lat, lon0, k0)
}

tm_rev_cpp <- function(x, y, lon0, k0) {
  .Call(`_geographiclib_tm_rev_cpp`, x, y, lon0, k0)
}

tm_exact_fwd_cpp <- function(lon, lat, lon0, k0) {
  .Call(`_geographiclib_tm_exact_fwd_cpp`, lon, lat, lon0, k0)
}

tm_exact_rev_cpp <- function(x, y, lon0, k0) {
  .Call(`_geographiclib_tm_exact_rev_cpp`, x, y, lon0, k0)
}

utmups_fwd_cpp <- function(lon, lat) {
  .Call(`_geographiclib_utmups_fwd_cpp`, lon, lat)
}

utmups_rev_cpp <- function(x, y, zone, northp) {
  .Call(`_geographiclib_utmups_rev_cpp`, x, y, zone, northp)
}
