# Generated by cpp11: do not edit by hand

mgrs_fwd_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_mgrs_fwd_cpp`, lon, lat, precision)
}

mgrs_rev_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_rev_cpp`, mgrs)
}

mgrs_decode_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_decode_cpp`, mgrs)
}

polygonarea_cpp <- function() {
  .Call(`_geographiclib_polygonarea_cpp`)
}
