# Generated by cpp11: do not edit by hand

geodesic_direct_cpp <- function(lon1, lat1, azi1, s12) {
  .Call(`_geographiclib_geodesic_direct_cpp`, lon1, lat1, azi1, s12)
}

geodesic_inverse_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_inverse_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_path_cpp <- function(lon1, lat1, lon2, lat2, n_points) {
  .Call(`_geographiclib_geodesic_path_cpp`, lon1, lat1, lon2, lat2, n_points)
}

geodesic_line_cpp <- function(lon1, lat1, azi1, distances) {
  .Call(`_geographiclib_geodesic_line_cpp`, lon1, lat1, azi1, distances)
}

geodesic_distance_matrix_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_matrix_cpp`, lon1, lat1, lon2, lat2)
}

geodesic_distance_pairwise_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_geodesic_distance_pairwise_cpp`, lon1, lat1, lon2, lat2)
}

geohash_fwd_cpp <- function(lon, lat, len) {
  .Call(`_geographiclib_geohash_fwd_cpp`, lon, lat, len)
}

geohash_rev_cpp <- function(geohash) {
  .Call(`_geographiclib_geohash_rev_cpp`, geohash)
}

geohash_resolution_cpp <- function(len) {
  .Call(`_geographiclib_geohash_resolution_cpp`, len)
}

geohash_length_for_precision_cpp <- function(resolution) {
  .Call(`_geographiclib_geohash_length_for_precision_cpp`, resolution)
}

geohash_length_for_precisions_cpp <- function(lat_resolution, lon_resolution) {
  .Call(`_geographiclib_geohash_length_for_precisions_cpp`, lat_resolution, lon_resolution)
}

lcc_fwd_cpp <- function(lon, lat, lon0, lat0, stdlat, k0) {
  .Call(`_geographiclib_lcc_fwd_cpp`, lon, lat, lon0, lat0, stdlat, k0)
}

lcc_fwd2_cpp <- function(lon, lat, lon0, lat0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_lcc_fwd2_cpp`, lon, lat, lon0, lat0, stdlat1, stdlat2, k1)
}

lcc_rev_cpp <- function(x, y, lon0, lat0, stdlat, k0) {
  .Call(`_geographiclib_lcc_rev_cpp`, x, y, lon0, lat0, stdlat, k0)
}

lcc_rev2_cpp <- function(x, y, lon0, lat0, stdlat1, stdlat2, k1) {
  .Call(`_geographiclib_lcc_rev2_cpp`, x, y, lon0, lat0, stdlat1, stdlat2, k1)
}

mgrs_fwd_cpp <- function(lon, lat, precision) {
  .Call(`_geographiclib_mgrs_fwd_cpp`, lon, lat, precision)
}

mgrs_rev_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_rev_cpp`, mgrs)
}

mgrs_decode_cpp <- function(mgrs) {
  .Call(`_geographiclib_mgrs_decode_cpp`, mgrs)
}

polygonarea_cpp <- function(lon, lat, id, polyline) {
  .Call(`_geographiclib_polygonarea_cpp`, lon, lat, id, polyline)
}

polygonarea_single_cpp <- function(lon, lat, polyline) {
  .Call(`_geographiclib_polygonarea_single_cpp`, lon, lat, polyline)
}

polygonarea_cumulative_cpp <- function(lon, lat, polyline) {
  .Call(`_geographiclib_polygonarea_cumulative_cpp`, lon, lat, polyline)
}

rhumb_direct_cpp <- function(lon1, lat1, azi12, s12) {
  .Call(`_geographiclib_rhumb_direct_cpp`, lon1, lat1, azi12, s12)
}

rhumb_inverse_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_inverse_cpp`, lon1, lat1, lon2, lat2)
}

rhumb_path_cpp <- function(lon1, lat1, lon2, lat2, n_points) {
  .Call(`_geographiclib_rhumb_path_cpp`, lon1, lat1, lon2, lat2, n_points)
}

rhumb_line_cpp <- function(lon1, lat1, azi12, distances) {
  .Call(`_geographiclib_rhumb_line_cpp`, lon1, lat1, azi12, distances)
}

rhumb_distance_pairwise_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_distance_pairwise_cpp`, lon1, lat1, lon2, lat2)
}

rhumb_distance_matrix_cpp <- function(lon1, lat1, lon2, lat2) {
  .Call(`_geographiclib_rhumb_distance_matrix_cpp`, lon1, lat1, lon2, lat2)
}

utmups_fwd_cpp <- function(lon, lat) {
  .Call(`_geographiclib_utmups_fwd_cpp`, lon, lat)
}

utmups_rev_cpp <- function(x, y, zone, northp) {
  .Call(`_geographiclib_utmups_rev_cpp`, x, y, zone, northp)
}
